# Generated by Django 5.0.4 on 2024-05-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db_AQDataRawDoc',
            new_name='db_AQDataRaw',
        ),
    ]
