# Generated by Django 5.0.4 on 2024-05-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_db_aqdataraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_AQDataRaw',
        ),
    ]
