# Generated by Django 5.0.4 on 2024-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_db_aqdataraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_AQDataRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
