# Generated by Django 5.0.4 on 2024-05-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_db_aqdata_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_AQData_Raw',
        ),
    ]
