# Generated by Django 5.0.4 on 2024-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_db_aqdata_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_AQData_Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='db_device',
            name='device_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
