# Generated by Django 5.0.4 on 2024-05-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_db_aqdata_raw_alter_db_device_device_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_AQData_Raw',
        ),
    ]
