# Generated by Django 5.0.4 on 2024-05-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_db_aqdata_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_device',
            name='parameters',
            field=models.CharField(max_length=100),
        ),
    ]
