# Generated by Django 5.0.4 on 2024-05-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_db_device_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_site',
            name='SITECol',
        ),
        migrations.AddField(
            model_name='db_site',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_host', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_host', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_host',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='address',
            field=models.TextField(default='NA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Location', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Location', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Network', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Network', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='person_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='person_mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='person_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_network',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_permission',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_permissions', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_permission',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_permissions', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_role',
            name='created_By',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='db_role',
            name='modified_By',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='db_role',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='db_site',
            name='HOST_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_host'),
        ),
        migrations.AlterField(
            model_name='db_site',
            name='Location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_location'),
        ),
        migrations.AlterField(
            model_name='db_site',
            name='NETWORK_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.db_network'),
        ),
        migrations.AlterField(
            model_name='db_site',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Sit', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_site',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Site', to='core.db_user'),
        ),
    ]
