# Generated by Django 5.0.4 on 2024-05-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_db_site_sitecol_db_site_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_devicemodel',
            name='classname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='company_url',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_DeviceModel', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='drivenname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='manual_url',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_DeviceModel', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_devicemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_location',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_manufacturer', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_manufacturer', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='person_Contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='person_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='person_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Vendor', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Vendor', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='person_Moblie',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='person_Title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='person_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_vendor',
            name='person_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
