# Generated by Django 5.0.4 on 2024-05-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_db_devicemodel_classname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_aqdatasparse',
            old_name='parameter',
            new_name='parameter_id',
        ),
        migrations.AddField(
            model_name='db_alertconfig',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db_alertconfig',
            name='create_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='db_alertconfig',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_AlterConfig', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_alertconfig',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_AlterConfig', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_alertconfig',
            name='modified_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='db_aqdatasparse',
            name='param_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='db_device',
            name='create_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_device',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Device', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_device',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Device', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_device',
            name='modified_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='db_parameter',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Parameter', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_parameter',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Parameter', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_site',
            name='Location_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.db_location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db_site',
            name='NETWORK_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.db_network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db_units',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_Units', to='core.db_user'),
        ),
        migrations.AlterField(
            model_name='db_units',
            name='modifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_Units', to='core.db_user'),
        ),
    ]
