# Generated by Django 5.0.4 on 2024-05-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_no_db_aqdata_no_rename_no2_db_aqdata_no2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_AirNet_Aggregated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PM10', models.FloatField()),
                ('CO', models.FloatField()),
                ('SO2', models.FloatField()),
                ('NO2', models.FloatField()),
                ('O3', models.FloatField()),
                ('NOx', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('rain_fall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('barometric_pressure', models.FloatField()),
                ('CO2', models.FloatField()),
                ('NO2_NV', models.FloatField()),
                ('CO_NV', models.FloatField()),
                ('O3_NV', models.FloatField()),
                ('SO2_NV', models.FloatField()),
                ('PM2_5', models.FloatField()),
                ('PM1_OPC', models.FloatField()),
                ('PM2_5_OPC', models.FloatField()),
                ('PM10_OPC', models.FloatField()),
                ('PM2_5_R', models.FloatField()),
                ('PM10_R', models.FloatField()),
                ('g1_RH', models.FloatField()),
                ('g1_T', models.FloatField()),
                ('g2_RH', models.FloatField()),
                ('g2_T', models.FloatField()),
                ('PM1', models.FloatField()),
                ('NO', models.FloatField()),
                ('NO_NV', models.FloatField()),
                ('status', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db_device')),
            ],
        ),
    ]
