# Generated by Django 5.0.4 on 2024-05-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_createdby_db_alertconfig_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_host',
            old_name='userId',
            new_name='user_id',
        ),
    ]
