# Generated by Django 5.0.4 on 2024-05-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_userid_db_host_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_site',
            old_name='HOST_id',
            new_name='host_id',
        ),
        migrations.RenameField(
            model_name='db_site',
            old_name='Location_id',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='db_site',
            old_name='NETWORK_id',
            new_name='network_id',
        ),
    ]
