# Generated by Django 5.0.4 on 2024-05-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_host_id_db_site_host_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_devicemodel',
            old_name='classname',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='db_devicemodel',
            old_name='drivenname',
            new_name='driver_name',
        ),
    ]
