# Generated by Django 5.0.4 on 2024-05-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_classname_db_devicemodel_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_device',
            old_name='DEVICEMODEL_ID',
            new_name='device_model_id',
        ),
        migrations.RenameField(
            model_name='db_device',
            old_name='installdt',
            new_name='install_dt',
        ),
        migrations.RenameField(
            model_name='db_device',
            old_name='LOCATIONS_ID',
            new_name='locations_id',
        ),
        migrations.RenameField(
            model_name='db_device',
            old_name='MANUFACTURER_ID',
            new_name='manufacturer_id',
        ),
        migrations.RenameField(
            model_name='db_device',
            old_name='NETWORK_ID',
            new_name='network_id',
        ),
        migrations.RenameField(
            model_name='db_device',
            old_name='SITE_ID',
            new_name='site_id',
        ),
        migrations.RenameField(
            model_name='db_device',
            old_name='VENDOR_ID',
            new_name='vendor_id',
        ),
        migrations.RenameField(
            model_name='db_vendor',
            old_name='person_Moblie',
            new_name='person_moblie',
        ),
        migrations.RenameField(
            model_name='db_vendor',
            old_name='person_Title',
            new_name='person_title',
        ),
    ]
