# Generated by Django 5.0.4 on 2024-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_israw_db_aqdatasparse_is_raw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_manufacturer_calibrated_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('o3_ppb', models.FloatField(null=True)),
                ('so2_ppb', models.FloatField(null=True)),
                ('no2_ppb', models.FloatField(null=True)),
                ('co_ppm', models.FloatField(null=True)),
                ('o3', models.FloatField(null=True)),
                ('so2', models.FloatField(null=True)),
                ('no2', models.FloatField(null=True)),
                ('co', models.FloatField(null=True)),
                ('pm25', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('ozone', models.FloatField(null=True)),
            ],
        ),
    ]
