# Generated by Django 5.0.4 on 2024-06-03 08:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_db_manufacturer_calibrated_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_aqdataext',
            name='measure_dt',
        ),
        migrations.AddField(
            model_name='db_manufacturer_calibrated_data',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 8, 57, 40, 81133, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_manufacturer_calibrated_data',
            name='device_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.db_device'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='db_missing_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('req_start_dt', models.DateTimeField()),
                ('req_end_dt', models.DateTimeField()),
                ('parameter', models.CharField(max_length=255)),
                ('error_code', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db_device')),
            ],
        ),
    ]
