# Generated by Django 5.0.4 on 2024-06-03 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_db_aqdataext_measure_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_aqdataext',
            name='measure_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 9, 3, 28, 936682, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
