# Generated by Django 5.0.4 on 2024-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_db_aqdataext_measure_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_device',
            name='parameters',
            field=models.CharField(max_length=1000),
        ),
    ]
