# Generated by Django 5.0.4 on 2024-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_db_device_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_missing_data',
            name='received_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
