# Generated by Django 5.0.4 on 2024-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_db_missing_data_received_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_missing_data',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
