# Generated by Django 5.0.4 on 2024-06-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_db_missing_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_manufacturer',
            name='access_id',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='access_key',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='api_or_pass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='auth_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='data_url',
            field=models.CharField(default='abc', max_length=2000),
            preserve_default=False,
        ),
    ]
