# Generated by Django 5.0.4 on 2024-06-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_db_manufacturer_access_id_db_manufacturer_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_manufacturer',
            name='access_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_manufacturer',
            name='access_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
