# Generated by Django 5.0.6 on 2024-06-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_db_missing_data_error_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_std_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pm10', models.FloatField(null=True)),
                ('co', models.FloatField(null=True)),
                ('so2', models.FloatField(null=True)),
                ('no2', models.FloatField(null=True)),
                ('o3', models.FloatField(null=True)),
                ('nox', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_direction', models.FloatField(null=True)),
                ('rain_fall', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('relative_humidity', models.FloatField(null=True)),
                ('barometric_pressure', models.FloatField(null=True)),
                ('co2', models.FloatField(null=True)),
                ('no2_nv', models.FloatField(null=True)),
                ('co_nv', models.FloatField(null=True)),
                ('o3_nv', models.FloatField(null=True)),
                ('so2_nv', models.FloatField(null=True)),
                ('pm2_5', models.FloatField(null=True)),
                ('pm1_opc', models.FloatField(null=True)),
                ('pm2_5_opc', models.FloatField(null=True)),
                ('pm10_opc', models.FloatField(null=True)),
                ('pm2_5_r', models.FloatField(null=True)),
                ('pm10_r', models.FloatField(null=True)),
                ('g1_rh', models.FloatField(null=True)),
                ('g1_t', models.FloatField(null=True)),
                ('g2_rh', models.FloatField(null=True)),
                ('g2_t', models.FloatField(null=True)),
                ('pm1', models.FloatField(null=True)),
                ('no', models.FloatField(null=True)),
                ('no_nv', models.FloatField(null=True)),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db_device')),
            ],
        ),
    ]
