# Generated by Django 5.0.6 on 2024-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_db_std_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_std_data',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
