# Generated by Django 5.0.6 on 2024-06-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_db_airnet_aggregated_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_airnet_aggregated',
            old_name='date_time',
            new_name='time',
        ),
    ]
