# Generated by Django 5.0.6 on 2024-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_rename_date_time_db_airnet_aggregated_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_manufacturer_calibrated_data',
            old_name='date_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='cal_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
