# Generated by Django 5.0.6 on 2024-06-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_db_manufacturer_calibrated_data_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_calibration_models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=255, null=True)),
                ('parameters', models.CharField(max_length=1000, null=True)),
                ('file_name1', models.CharField(max_length=1000, null=True)),
                ('dt_time', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.db_device')),
            ],
        ),
    ]
