# Generated by Django 5.0.6 on 2024-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_db_calibration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_missing_data',
            name='error_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='db_missing_data',
            name='parameter',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
