# Generated by Django 5.0.6 on 2024-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_db_manufacturer_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_manufacturer',
            name='accept',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='client_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='grant_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='db_manufacturer',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
