# Generated by Django 5.0.6 on 2024-06-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20240619_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_audit_trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_time', models.DateTimeField(auto_now_add=True)),
                ('activity_code', models.CharField(max_length=50)),
                ('activity_desc', models.CharField(max_length=1000)),
                ('param1', models.CharField(max_length=255, null=True)),
                ('param2', models.CharField(max_length=255, null=True)),
                ('param3', models.CharField(max_length=255, null=True)),
                ('severity', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Audit_user', to='core.db_user')),
            ],
        ),
    ]
