# Generated by Django 5.0.6 on 2024-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_db_device_is_reference_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='db_std_data',
            unique_together={('device_id', 'time')},
        ),
    ]
