# Generated by Django 5.0.6 on 2024-06-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_db_std_data_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_aqdata',
            old_name='date_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='db_airnet_aggregated',
            unique_together={('device_id', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='db_aqdata',
            unique_together={('device_id', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='db_manufacturer_calibrated_data',
            unique_together={('device_id', 'time')},
        ),
    ]
