# Generated by Django 5.0.4 on 2024-05-21 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_aqdata_raw',
            name='httpCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='db_aqdata_raw',
            name='isCalibrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_aqdata_raw',
            name='manufacturer',
            field=models.CharField(default='random', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_aqdata_raw',
            name='request_url',
            field=models.CharField(default='url', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_aqdata_raw',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
