# Generated by Django 5.0.4 on 2024-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0002_db_aqdata_raw_httpcode_db_aqdata_raw_iscalibrated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_aqdata_raw',
            name='processed_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
