# Generated by Django 5.0.4 on 2024-05-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0005_db_airnet_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_airnet_raw',
            name='data_cal',
            field=models.JSONField(null=True),
        ),
    ]
