# Generated by Django 5.0.4 on 2024-05-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0006_alter_db_airnet_raw_data_cal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='db_AirNet_Raw_Reponse',
            new_name='db_AirNet_Raw_Response',
        ),
    ]
