# Generated by Django 5.0.4 on 2024-05-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0007_rename_db_airnet_raw_reponse_db_airnet_raw_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_airnet_raw_response',
            old_name='httpCode',
            new_name='http_code',
        ),
        migrations.RenameField(
            model_name='db_airnet_raw_response',
            old_name='isCalibrated',
            new_name='is_calibrated',
        ),
    ]
