# Generated by Django 5.0.6 on 2024-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0009_db_airnet_raw_response_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_airnet_raw_response',
            name='pollutant',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
